// Code generated by scripts/gen-attack-catalog.mjs. DO NOT EDIT.
//
// Source of truth: client/src/data/attacks.js. Regenerate with
//   node scripts/gen-attack-catalog.mjs

package utils

// AttackNames maps each attack id to its display name.
var AttackNames = map[string]string{
	"app-dos": "Application-Layer Denial of Service",
	"authentication-bypass": "Authentication Bypass",
	"cors-misconfiguration": "CORS Misconfiguration",
	"csrf": "Cross-Site Request Forgery (CSRF)",
	"file-upload": "Malicious File Upload",
	"graphql-abuse": "GraphQL API Abuse",
	"http-request-smuggling": "HTTP Request Smuggling",
	"idor": "Insecure Direct Object Reference (IDOR)",
	"insecure-deserialization": "Insecure Deserialization",
	"jwt-attacks": "JWT Attacks",
	"ldap-injection": "LDAP Injection",
	"log-injection": "Log Injection and Forging",
	"mass-assignment": "Mass Assignment (Autobinding)",
	"nosql-injection": "NoSQL Injection",
	"oauth-account-takeover": "OAuth 2.0 / OpenID Connect Abuse",
	"open-redirect": "Open Redirect",
	"os-command-injection": "OS Command Injection",
	"path-traversal-lfi": "Path Traversal and File Inclusion (LFI/RFI)",
	"prototype-pollution": "Prototype Pollution",
	"race-condition": "Race Condition (TOCTOU)",
	"sql-injection": "SQL Injection",
	"ssrf": "Server-Side Request Forgery (SSRF)",
	"ssti": "Server-Side Template Injection (SSTI)",
	"web-cache-poisoning": "Web Cache Poisoning & Deception",
	"xpath-injection": "XPath / XQuery Injection",
	"xss": "Cross-Site Scripting (XSS)",
	"xxe": "XML External Entity (XXE)",
}

// AttackCategories lists the STRIDE categories each attack can be weaponized to achieve.
// A threat may only cite an attack that covers the threat's own category.
var AttackCategories = map[string][]string{
	"app-dos": {"denial_of_service"},
	"authentication-bypass": {"spoofing", "elevation_of_privilege"},
	"cors-misconfiguration": {"spoofing", "information_disclosure"},
	"csrf": {"spoofing", "tampering", "elevation_of_privilege"},
	"file-upload": {"spoofing", "tampering", "information_disclosure", "denial_of_service", "elevation_of_privilege"},
	"graphql-abuse": {"tampering", "information_disclosure", "denial_of_service", "elevation_of_privilege"},
	"http-request-smuggling": {"spoofing", "tampering", "information_disclosure", "elevation_of_privilege"},
	"idor": {"tampering", "information_disclosure", "elevation_of_privilege"},
	"insecure-deserialization": {"tampering", "denial_of_service", "elevation_of_privilege"},
	"jwt-attacks": {"spoofing", "tampering", "elevation_of_privilege"},
	"ldap-injection": {"spoofing", "information_disclosure", "elevation_of_privilege"},
	"log-injection": {"tampering", "repudiation"},
	"mass-assignment": {"spoofing", "tampering", "elevation_of_privilege"},
	"nosql-injection": {"spoofing", "tampering", "information_disclosure", "denial_of_service", "elevation_of_privilege"},
	"oauth-account-takeover": {"spoofing", "information_disclosure", "elevation_of_privilege"},
	"open-redirect": {"spoofing", "information_disclosure", "elevation_of_privilege"},
	"os-command-injection": {"tampering", "information_disclosure", "denial_of_service", "elevation_of_privilege"},
	"path-traversal-lfi": {"information_disclosure", "denial_of_service", "elevation_of_privilege"},
	"prototype-pollution": {"tampering", "information_disclosure", "denial_of_service", "elevation_of_privilege"},
	"race-condition": {"spoofing", "tampering", "elevation_of_privilege"},
	"sql-injection": {"spoofing", "tampering", "information_disclosure", "denial_of_service", "elevation_of_privilege"},
	"ssrf": {"spoofing", "information_disclosure", "denial_of_service", "elevation_of_privilege"},
	"ssti": {"tampering", "information_disclosure", "elevation_of_privilege"},
	"web-cache-poisoning": {"tampering", "information_disclosure", "denial_of_service"},
	"xpath-injection": {"spoofing", "information_disclosure", "elevation_of_privilege"},
	"xss": {"spoofing", "tampering", "information_disclosure", "elevation_of_privilege"},
	"xxe": {"information_disclosure", "denial_of_service", "elevation_of_privilege"},
}

// IsValidAttackForCategory reports whether attackID is a known attack that is weaponized
// to achieve category. An empty attackID is not valid: callers that allow "not yet tied to
// an attack" must check for empty themselves, so the permission is explicit at each site.
func IsValidAttackForCategory(attackID, category string) bool {
	for _, c := range AttackCategories[attackID] {
		if c == category {
			return true
		}
	}
	return false
}
