package utils

// Runs the SAME vectors the JavaScript evaluator runs.
//
// scope/vectors.json is generated by `node extension/scoperules.test.mjs --emit`. If this test
// fails, the two evaluators disagree, and that is a security bug rather than a tidiness one: the
// extension would record a host the scanner refuses, or the scanner would contact a host the
// operator believes is excluded. Fix the disagreement; do not regenerate the vectors to match Go.

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

type vectorFile struct {
	Authorities []struct {
		Input  string `json:"input"`
		Scheme string `json:"scheme"`
		Expect *struct {
			Host string `json:"host"`
			Port int    `json:"port"`
			IsIP bool   `json:"isIP"`
		} `json:"expect"`
	} `json:"authorities"`

	Rules []struct {
		Typed  string `json:"typed"`
		Expect struct {
			Error  bool    `json:"error"`
			Effect string  `json:"effect"`
			Kind   string  `json:"kind"`
			Value  string  `json:"value"`
			Port   *int    `json:"port"`
			Within *string `json:"within"`
			Blast  string  `json:"blast"`
		} `json:"expect"`
	} `json:"rules"`

	Decisions []struct {
		Rules         []string `json:"rules"`
		Subject       string   `json:"subject"`
		AdmitObserved bool     `json:"admitObserved"`
		Observed      []string `json:"observed"`
		Expect        struct {
			Allowed bool   `json:"allowed"`
			Reason  string `json:"reason"`
		} `json:"expect"`
	} `json:"decisions"`
}

func loadVectors(t *testing.T) vectorFile {
	t.Helper()
	// server/utils -> repo root
	path := filepath.Join("..", "..", "scope", "vectors.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("cannot read %s: %v\nRegenerate with: node extension/scoperules.test.mjs --emit", path, err)
	}
	var vf vectorFile
	if err := json.Unmarshal(raw, &vf); err != nil {
		t.Fatalf("cannot parse %s: %v", path, err)
	}
	return vf
}

func TestScopeVectorsAuthorities(t *testing.T) {
	vf := loadVectors(t)
	if len(vf.Authorities) == 0 {
		t.Fatal("no authority vectors")
	}
	for _, v := range vf.Authorities {
		got, ok := NormalizeAuthority(v.Input, v.Scheme)
		if v.Expect == nil {
			if ok {
				t.Errorf("NormalizeAuthority(%q, %q) = %+v, want rejection", v.Input, v.Scheme, got)
			}
			continue
		}
		if !ok {
			t.Errorf("NormalizeAuthority(%q, %q) rejected, want %+v", v.Input, v.Scheme, *v.Expect)
			continue
		}
		if got.Host != v.Expect.Host || got.Port != v.Expect.Port || got.IsIP != v.Expect.IsIP {
			t.Errorf("NormalizeAuthority(%q, %q) = {%s %d %v}, want {%s %d %v}",
				v.Input, v.Scheme, got.Host, got.Port, got.IsIP,
				v.Expect.Host, v.Expect.Port, v.Expect.IsIP)
		}
	}
}

func TestScopeVectorsRules(t *testing.T) {
	vf := loadVectors(t)
	if len(vf.Rules) == 0 {
		t.Fatal("no rule vectors")
	}
	for _, v := range vf.Rules {
		got, err := ParseScopeRule(v.Typed)
		if v.Expect.Error {
			if err == nil {
				t.Errorf("ParseScopeRule(%q) = %+v, want an error", v.Typed, got)
			}
			continue
		}
		if err != nil {
			t.Errorf("ParseScopeRule(%q) failed: %v", v.Typed, err)
			continue
		}
		wantPort := 0
		if v.Expect.Port != nil {
			wantPort = *v.Expect.Port
		}
		wantWithin := ""
		if v.Expect.Within != nil {
			wantWithin = *v.Expect.Within
		}
		if string(got.Effect) != v.Expect.Effect || string(got.Kind) != v.Expect.Kind ||
			got.Value != v.Expect.Value || got.Port != wantPort ||
			got.Within != wantWithin || string(got.Blast) != v.Expect.Blast {
			t.Errorf("ParseScopeRule(%q)\n got  effect=%s kind=%s value=%s port=%d within=%s blast=%s\n want effect=%s kind=%s value=%s port=%d within=%s blast=%s",
				v.Typed, got.Effect, got.Kind, got.Value, got.Port, got.Within, got.Blast,
				v.Expect.Effect, v.Expect.Kind, v.Expect.Value, wantPort, wantWithin, v.Expect.Blast)
		}
	}
}

func TestScopeVectorsDecisions(t *testing.T) {
	vf := loadVectors(t)
	if len(vf.Decisions) == 0 {
		t.Fatal("no decision vectors")
	}
	for _, v := range vf.Decisions {
		rules := make([]ScopeRule, 0, len(v.Rules))
		bad := false
		for _, typed := range v.Rules {
			r, err := ParseScopeRule(typed)
			if err != nil {
				t.Errorf("vector rule %q did not parse: %v", typed, err)
				bad = true
				break
			}
			rules = append(rules, r)
		}
		if bad {
			continue
		}

		in := ScopeDecisionInput{AdmitObserved: v.AdmitObserved}
		if len(v.Observed) > 0 {
			in.Observed = map[string]bool{}
			for _, o := range v.Observed {
				in.Observed[o] = true
			}
		}

		auth, ok := NormalizeAuthority(v.Subject, "")
		got := DecideScope(rules, auth, ok, in)
		if got.Allowed != v.Expect.Allowed || got.Reason != v.Expect.Reason {
			t.Errorf("DecideScope(%v, %q) = {allowed=%v reason=%s}, want {allowed=%v reason=%s}",
				v.Rules, v.Subject, got.Allowed, got.Reason, v.Expect.Allowed, v.Expect.Reason)
		}
	}
}

// Deny beating allow must not depend on the order rules arrive in. The vectors pin specific pairs;
// this pins the property itself across every permutation of a representative set.
func TestScopeDenyWinsRegardlessOfOrder(t *testing.T) {
	typed := []string{"example.com", "~jivo", "!cdn.example.com", "*.api.example.com"}
	subject, ok := NormalizeAuthority("https://eu.cdn.example.com/", "")
	if !ok {
		t.Fatal("subject did not normalise")
	}

	var permute func([]string, int)
	checked := 0
	permute = func(list []string, k int) {
		if k == len(list) {
			rules := make([]ScopeRule, 0, len(list))
			for _, s := range list {
				r, err := ParseScopeRule(s)
				if err != nil {
					t.Fatalf("rule %q: %v", s, err)
				}
				rules = append(rules, r)
			}
			v := DecideScope(rules, subject, true, ScopeDecisionInput{})
			if v.Allowed || v.Reason != "rule_deny" {
				t.Errorf("order %v gave {allowed=%v reason=%s}, want denied", list, v.Allowed, v.Reason)
			}
			checked++
			return
		}
		for i := k; i < len(list); i++ {
			list[k], list[i] = list[i], list[k]
			permute(list, k+1)
			list[k], list[i] = list[i], list[k]
		}
	}
	permute(typed, 0)
	if checked != 24 {
		t.Errorf("checked %d permutations, want 24", checked)
	}
}

// An uncompilable stored rule must fail the whole target closed rather than being skipped.
func TestScopeUncompilableRuleFailsClosed(t *testing.T) {
	rules := []ScopeRule{
		{Effect: EffectAllow, Kind: KindSubtree, Value: "example.com", Enabled: true},
		{Effect: EffectDeny, Kind: KindRegex, Value: "([a-z]", Enabled: true, ID: "bad"},
	}
	if _, err := CompileScopeRules(rules); err == nil {
		t.Fatal("CompileScopeRules accepted an uncompilable pattern; it must fail the target closed")
	}
}

// The canonical form must re-parse to itself, or the stored rule and the typed rule drift apart and
// the UI shows a sentence the engine never agreed to.
func TestScopeCanonicalRoundTrip(t *testing.T) {
	for _, typed := range []string{
		"example.com", "*.example.com", "=api.example.com", "=app.example.com:8443",
		"~jivo", "~jivo within acme.io", "!cdn.example.com", "!=cdn.example.com",
		"!*.cdn.example.com", `re:prod-[0-9]+\.acme\.io`, "=10.0.0.18", "=[2001:db8::5]",
	} {
		first, err := ParseScopeRule(typed)
		if err != nil {
			t.Errorf("ParseScopeRule(%q): %v", typed, err)
			continue
		}
		text := CanonicalScopeText(first)
		second, err := ParseScopeRule(text)
		if err != nil {
			t.Errorf("canonical %q from %q did not re-parse: %v", text, typed, err)
			continue
		}
		if again := CanonicalScopeText(second); again != text {
			t.Errorf("round trip %q: %q -> %q", typed, text, again)
		}
	}
}

// The lookalike class, pinned independently of the vectors so it survives a vector regeneration.
func TestScopeLookalikesAreOutside(t *testing.T) {
	rule, err := ParseScopeRule("example.com")
	if err != nil {
		t.Fatal(err)
	}
	for _, host := range []string{
		"https://notexample.com/", "https://example.com.evil.test/", "https://xexample.com/",
		"https://example.com.attacker.net/",
	} {
		if URLInScope(host, []ScopeRule{rule}, ScopeDecisionInput{}) {
			t.Errorf("%s must be outside the boundary of example.com", host)
		}
	}
	for _, host := range []string{"https://example.com/", "https://api.example.com/", "https://a.b.example.com/"} {
		if !URLInScope(host, []ScopeRule{rule}, ScopeDecisionInput{}) {
			t.Errorf("%s must be inside the boundary of example.com", host)
		}
	}
}

// Authored rules must actually gate ScanScope, which is the boundary that decides what leaves the
// machine. Without this, the rule engine could be perfect and still enforce nothing.
func TestScanScopeHonoursAuthoredRules(t *testing.T) {
	mustRule := func(typed string) ScopeRule {
		r, err := ParseScopeRule(typed)
		if err != nil {
			t.Fatalf("rule %q: %v", typed, err)
		}
		return r
	}

	s := &ScanScope{
		primary: "app.jivosite.com",
		domains: map[string]bool{"jivosite.com": true},
		extra:   map[string]bool{},
		refused: map[string]int{},
		rules: []ScopeRule{
			mustRule("~jivo"),
			mustRule("!=telemetry.jivosite.com"),
			mustRule("*.jivosite.com"),
		},
	}

	cases := []struct {
		host string
		want bool
		why  string
	}{
		{"api.jivosite.com", true, "matches both ~jivo and *.jivosite.com"},
		{"telemetry.jivosite.com", false, "explicit deny beats both allows"},
		{"jivosite.com", true, "apex excluded by *. but still admitted by ~jivo"},
		{"myjivo-clone.attacker.test", true, "contains genuinely matches a lookalike: the documented cost of ~"},
		{"example.com", false, "no rule matches, so default deny"},
		// The legacy fields are deliberately NOT consulted once rules exist. app.jivosite.com is
		// s.primary, which the old path allowed unconditionally; here it is allowed only because a
		// rule matches it. If a deny covered it, it would be refused despite being primary.
		{"app.jivosite.com", true, "allowed by rule, not by being primary"},
	}
	for _, c := range cases {
		if got := s.Allows(c.host); got != c.want {
			t.Errorf("Allows(%q) = %v, want %v (%s)", c.host, got, c.want, c.why)
		}
	}

	// A deny must override even the primary host, or "deny wins" is not true at the boundary.
	s.rules = append(s.rules, mustRule("!=app.jivosite.com"))
	if s.Allows("app.jivosite.com") {
		t.Error("a deny rule must override the primary host; it is the operator's emergency stop")
	}

	// A target whose rules could not be loaded refuses everything rather than falling back to the
	// wider legacy boundary. Falling back is the failure mode where a deny fails to load and
	// traffic goes out anyway.
	refusing := &ScanScope{refuseAll: true}
	if refusing.Allows("app.jivosite.com") {
		t.Error("a scope that failed to load its rules must refuse everything")
	}
}

// Userinfo is attacker-chosen text and must never reach a contains rule.
func TestScopeUserinfoStripped(t *testing.T) {
	rule, err := ParseScopeRule("~jivo")
	if err != nil {
		t.Fatal(err)
	}
	if URLInScope("https://jivo@attacker.test/", []ScopeRule{rule}, ScopeDecisionInput{}) {
		t.Error("userinfo reached the matcher: an attacker could put any string before the '@'")
	}
}
